version: '3.9'

services:

  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
