version: '3.9'

services:

  mongo:
    container_name: mongodb
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data-db:/data/db
      - mongodb-data-config-db:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      TZ: America/Sao_Paulo

volumes:
  mongodb-data-db:
  mongodb-data-config-db:
