version: '3.9'

services:

  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo

  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      MONGODB_URI: mongodb://mongo:mongo@mongo:27017/mongo?authSource=admin

  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    depends_on:
      - backend
    ports:
      - 4200:80
